### PR TITLE
Feat/generics

### PR DESCRIPTION
**Pull request by Antonboom**
Closes https://github.com/kazhuravlev/options-gen/issues/14

It was fun ))) 🤯🤯🤯

I think we should consider generics support as experimental feature, that requires a lot of testing.

### CODE REVIEW

**Comment by kazhuravlev** [comment]
Wow! It is brilliant. I need some time to test it in real projects.

**Review by kazhuravlev — CHANGES_REQUESTED** [review]
Perfect!

- Add tests with generic options for `generator.GetOptionSpec`

**Comment by Antonboom** [comment]
> Add tests with generic options for generator.GetOptionSpec

Done.

**Review by kazhuravlev — APPROVED** [review]
Thanks, pretty cool!

**Pull request merged**
